
package game.network.packet;
class Command
{
    public static var CMD_USER_LOGIN: Int = 100;
    public static var CMD_RESP_USERINFO: Int = 101;
    public static var CMD_USER_UPGRADE_POWER: Int = 102;
    public static var CMD_RESP_UPGRADE_POWER_MAIN: Int = 103;
    public static var CMD_RESP_UPGRADE_POWER_SUB: Int = 104;
    public static var CMD_GAME_DUNGEON_ENTER: Int = 200;
    public static var CMD_GAME_ENTER: Int = 201;
    public static var CMD_GAME_PVE_ENTER: Int = 202;
    public static var CMD_GAME_MATCH: Int = 203;
    public static var CMD_GAME_ASK_LOSE: Int = 204;
    public static var CMD_GAME_SYN_TIME: Int = 205;
    public static var CMD_GAME_ACTIVE_SKILL: Int = 206;
    public static var CMD_RESP_ANSWER_LOSE: Int = 207;
    public static var CMD_RESP_SYN_TIME_MONSTER: Int = 208;
    public static var CMD_RESP_ENTER: Int = 209;
    public static var CMD_RESP_MATCH: Int = 210;
    public static var CMD_RESP_WIN: Int = 211;
    public static var CMD_RESP_LOSE: Int = 212;
    public static var CMD_RESP_ENTER_DUNGEON: Int = 213;
    public static var CMD_RESP_ENTER_PVP: Int = 214;
    public static var CMD_RESP_ENTER_PVP_NO_COMPETITOR: Int = 215;
    public static var CMD_RESP_MATCH_PVP: Int = 216;
    public static var CMD_RESP_WIN_PVP: Int = 217;
    public static var CMD_RESP_LOSE_PVP: Int = 218;
    public static var CMD_RESP_ENTER_PVE: Int = 219;
    public static var CMD_RESP_MATCH_PVE: Int = 220;
    public static var CMD_RESP_WIN_PVE: Int = 221;
    public static var CMD_RESP_LOSE_PVE: Int = 222;
    public static var CMD_RESP_BATTLE_SKILL_SILENT: Int = 223;
    public static var CMD_RESP_BATTLE_SKILL_FIRE: Int = 224;
    public static var CMD_RESP_BATTLE_SKILL_HP: Int = 225;
    public static var CMD_RESP_BATTLE_SKILL_FREEZE: Int = 226;
    public static var CMD_RESP_BATTLE_SKILL_CLEAN_MINE: Int = 227;
    public static var CMD_RESP_BATTLE_SKILL_CLEAN_ENEMY: Int = 228;
    public static var CMD_RESP_BATTLE_SKILL_DEFENSE: Int = 229;
    public static var CMD_RESP_BATTLE_SKILL_SUCK: Int = 230;
    public static var CMD_RESP_BATTLE_SKILL_OBSTACLES_SET: Int = 231;
    public static var CMD_RESP_BATTLE_SKILL_GEMS_SET: Int = 232;
    public static var CMD_UPDATE_ITEMSET: Int = 250;
    public static var CMD_ADD_AUX_ITEM: Int = 251;
    public static var CMD_REMOVE_AUX_ITEM: Int = 252;
    public static var CMD_UPGRADE_ITEM: Int = 253;
    public static var CMD_RESP_ITEM: Int = 254;
    public static var CMD_SKILL_CHOOSE: Int = 270;
    public static var CMD_RESP_SKILL: Int = 271;
    public static var CMD_CHAT_SEND: Int = 280;
    public static var CMD_RESP_CHAT_MSG: Int = 281;
    public static var CMD_RESP_CHAT_BAN: Int = 282;
    public static var CMD_CHEAT: Int = 290;
    public static var CMD_RESP_CHEAT_GOLD: Int = 291;
    public static var CMD_RESP_CHEAT_COIN: Int = 292;
}
